### ISSUE TITLE
Operation: ( remove ) failed on key: [(a shard in) DECISION ]

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [Netflix/dyno-queues#96]
Hello.

I have a lot of tasks running on Conductor. When my workers are trying to execute them on polling, conductor responds with that kind of error

     {"code":"INTERNAL_ERROR","message":"INTERNAL_ERROR - Operation: ( remove ) failed on key: [(a shard in) DECISION ].","retryable":false,"instance":"18eb47ff475b"}

What is the meaning of this error?

**Comment by smukil** [comment]
The above errors could likely be due to a failure in achieving quorum or the dynomite server node(s) are unreachable temporarily (you would see other related errors in the logs if this is the case).

If you have no other information in the logs, the best way to figure out the actual error would be to attach a debugger to your java process and add breakpoints in remove() and step in to see what's going on.

Also, please see the updated README for the project status.

**Comment by manan164** [comment]
Hi @smukil , I see that if we revert the [commit](https://github.com/Netflix/dyno-queues/commit/52f79ee435924aa2ce38e8c3bd18f2dbaab9b9cb) then it is working fine. But commit says it fixes the removal part. I see that every time removed is 0 so it won't take if condiction path and a message from the queue will not get removed and it just gets piled up.
